### PR TITLE
Date Operations

### LINKED ISSUE #108: All Date Operations
Should add all date operations for Date, LocalDate, Timestamp.

### PR DESCRIPTION
**Pull request by rleibman**
Fixes #108 

### Problem

Explain here the context, and why you're making that change.
What is the problem you're trying to solve?

### Solution

Describe the modifications you've done.

### Notes

Additional notes.

### Checklist

- [ ] Unit test all changes
- [ ] Update `README.md` if applicable
- [ ] Add `[WIP]` to the pull request title if it's work in progress
- [ ] [Squash commits](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one) that aren't meaningful changes

@getquill/maintainers

### CODE REVIEW

**Comment by guizmaii** [comment]
@rleibman Can you rebase your PR, please?

**Comment by rleibman** [comment]
Boom there it is.

**Comment by guizmaii** [comment]
Thanks! 😄
Compilation fails tho 😅

**Comment by rleibman** [comment]
I would love to fix it, but it doesn't build locally: 
```=== End Selected Modules ===
[info] loading settings for project quill from build.sbt ...
[info] resolving key references (15659 settings) ...
java.lang.RuntimeException: Some keys were defined with the same name but different types: 'gitReader' (com.github.sbt.git.ReadableGit, com.typesafe.sbt.git.ReadableGit), 'gitRunner' (sbt.Task[com.typesafe.sbt.git.GitRunner], sbt.Task[com.github.sbt.git.GitRunner])
```

**Comment by guizmaii** [comment]
@rleibman Did you configure any "global sbt plugins"?

**Comment by rleibman** [comment]
Yeah, there's an incompatibility somewhere with sbt-prompt!

**Comment by rleibman** [comment]
ok, I fixed some of the compiler errors in Dsl.scala, but in Parser.scala, there's some errors I'm not sure how to fix, and if they are very deep and require a lot of knowledge of internals of quill I'm not sure how much effort I want to put into them:
```scala
/Users/rleibman/projects/other/zio-protoquill/quill-sql/src/main/scala/io/getquill/parser/Parser.scala:893:64
Found:    (a : ExtrasParser.this.x$2.reflect.Term)
Required: quoted.Expr[?]
```

**Pull request closed without merging**
