### PR TITLE
Update Scala to `3.3.0`, sbt to `1.9.0`, HikariCP to `4.0.3` and `scala-java8-compat` to `1.0.2`

### PR DESCRIPTION
**Pull request by guizmaii**

### CODE REVIEW

**Comment by prolativ** [comment]
@guizmaii have you tried removing `inline` from `using inline path: Path[F, T]`? I haven't tried running the tests but they seem to compile after the change

**Comment by prolativ** [comment]
@guizmaii The same change has to be made also in `TypelevelUsecase_WithPassin.scala`

**Comment by guizmaii** [comment]
@prolativ Thanks! I updated my commit https://github.com/zio/zio-protoquill/pull/276/commits/bfbb10f282475c12f076b3f8688debc0ec5a33aa

**Comment by guizmaii** [comment]
@prolativ  The code does indeed compile with these changes. Thanks :)

We'll see if the CI passes

**Comment by guizmaii** [comment]
Tests are passing 🎉 

Thanks for your help @prolativ 🙏

**Review by juliano — APPROVED** [review]
lgtm

**Pull request merged**
